//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statue
    {
        public decimal Statue_Number { get; set; }
        public string Character { get; set; }
        public string Manufacturer { get; set; }
        public string Scale { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Edition_Size { get; set; }
        public bool Owned { get; set; }
        public string Cape_Style { get; set; }
        public string Hair_Type { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public bool Kit { get; set; }
        public Nullable<decimal> Order_Number { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Retailer { get; set; }
        public Nullable<decimal> Payment_Length { get; set; }
        public Nullable<decimal> Payment_Cost { get; set; }
        public Nullable<decimal> Non_Refundable_Deposit { get; set; }
        public Nullable<bool> Paid { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Number_Of_Boxes { get; set; }
        public Nullable<bool> Exclusive { get; set; }
        public string Material { get; set; }
    } //Lots of properties!
}
